'use client';

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { 
  Book, 
  HelpCircle, 
  ShieldCheck, 
  Zap, 
  Smartphone, 
  Laptop, 
  Database, 
  MessageSquare, 
  ChevronRight, 
  ArrowLeft,
  GraduationCap,
  Scale,
  Sparkles,
  ClipboardList,
  Fingerprint
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { cn } from '@/lib/utils';

export default function SystemManualPage() {
  const router = useRouter();

  const sections = [
    {
      id: 'attendance',
      title: 'Identity & Presence',
      icon: Fingerprint,
      content: [
        { subtitle: 'HUD Scan Terminal', desc: 'Students must use their physical device to scan dynamic QR tokens generated by faculty. Tokens are encrypted and refresh every 60 seconds to ensure session integrity.' },
        { subtitle: 'Correction Challenges', desc: 'If a session presence is missed or misaligned, students can initiate an audit challenge via their Attendance History page. Faculty review these challenges with evidentiary support.' }
      ]
    },
    {
      id: 'academics',
      title: 'AI Study HUD',
      icon: Sparkles,
      content: [
        { subtitle: 'Material Synthesis', desc: 'Use the "Summarize" node on any study material to receive a condensed AI-driven overview of core concepts, optimized for quick revision.' },
        { subtitle: 'Cognitive Drills', desc: 'Generate interactive practice quizzes and questions from course assets. The AI evaluation matrix provides immediate rationale for correct answers.' }
      ]
    },
    {
      id: 'finance',
      title: 'Financial Ledger',
      icon: Scale,
      content: [
        { subtitle: 'Settlement Flow', desc: 'Institutional dues are settleable through the "Fees" module. The platform maintains a chronological ledger of all processed and outstanding balances.' },
        { subtitle: 'Admin Bulk Actions', desc: 'System administrators utilize the bulk assignment engine to provision term-wide fees across the entire student directory simultaneously.' }
      ]
    },
    {
      id: 'social',
      title: 'Social Engagement',
      icon: MessageSquare,
      content: [
        { subtitle: 'Academic Forums', desc: 'Participate in subject-specific discourse. Entries are synchronized across the institutional ledger and subject to automated moderation.' },
        { subtitle: 'Student Guilds', desc: 'Join clubs to build a collective identity. Members receive priority access to specialized departmental workshops and seminars.' }
      ]
    }
  ];

  return (
    <div className="flex flex-col gap-8 pb-12 animate-in fade-in duration-1000">
      <div className="academic-hero">
          <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
              <div className="space-y-4">
                  <Button variant="outline" size="sm" className="bg-white/10 border-white/20 text-white hover:bg-white/20 rounded-xl" onClick={() => router.back()}>
                      <ArrowLeft className="mr-2 h-4 w-4" /> Return to Workspace
                  </Button>
                  <div className="space-y-1">
                      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 border border-white/20 text-white/90 text-[10px] font-black uppercase tracking-widest backdrop-blur-sm">
                          <Book className="h-3 w-3" /> Knowledge Base
                      </div>
                      <h1 className="text-4xl md:text-5xl font-black tracking-tighter uppercase leading-none">SYSTEM MANUAL</h1>
                      <p className="text-indigo-100/70 font-medium max-w-2xl leading-relaxed">
                          Your guide to navigating the Campus Connect digital ecosystem. Explore module protocols and learn how to leverage AI-driven academic tools.
                      </p>
                  </div>
              </div>
              <div className="hidden lg:block opacity-20"><HelpCircle className="h-32 w-32" /></div>
          </div>
      </div>

      <div className="grid gap-8 lg:grid-cols-12">
          <div className="lg:col-span-8">
              <Tabs defaultValue="attendance" className="w-full">
                  <TabsList className="flex flex-wrap w-full h-auto p-1 bg-white/50 backdrop-blur-sm border rounded-2xl overflow-x-auto">
                      {sections.map(s => (
                          <TabsTrigger key={s.id} value={s.id} className="flex-1 min-w-[120px] rounded-xl font-black uppercase text-[9px] tracking-widest py-3">
                              {s.title}
                          </TabsTrigger>
                      ))}
                  </TabsList>

                  {sections.map(s => (
                      <TabsContent key={s.id} value={s.id} className="mt-8 space-y-6">
                          {s.content.map((item, idx) => (
                              <Card key={idx} className="glass-card border-none overflow-hidden group">
                                  <CardHeader className="bg-primary/5 border-b border-white/10">
                                      <div className="flex items-center gap-4">
                                          <div className="bg-white p-3 rounded-2xl shadow-sm text-primary group-hover:scale-110 transition-transform">
                                              <s.icon className="h-5 w-5" />
                                          </div>
                                          <CardTitle className="text-lg font-black uppercase tracking-tight">{item.subtitle}</CardTitle>
                                      </div>
                                  </CardHeader>
                                  <CardContent className="pt-6">
                                      <p className="text-slate-600 leading-relaxed font-medium">
                                          {item.desc}
                                      </p>
                                  </CardContent>
                              </Card>
                          ))}
                      </TabsContent>
                  ))}
              </Tabs>
          </div>

          <div className="lg:col-span-4 space-y-8">
              <Card className="glass-card border-none bg-indigo-500 text-white overflow-hidden shadow-indigo-500/20 shadow-2xl">
                  <CardHeader className="bg-black/10">
                      <CardTitle className="text-sm font-black uppercase tracking-widest opacity-80">Platform Mission</CardTitle>
                  </CardHeader>
                  <CardContent className="pt-8 space-y-6">
                      <div className="bg-white/10 p-6 rounded-[2rem] border border-white/10 backdrop-blur-xl">
                          <GraduationCap className="h-8 w-8 mb-4 opacity-50" />
                          <p className="text-lg font-medium leading-tight">
                              "To bridge the gap between academic and administrative layers through a unified, secure digital ledger."
                          </p>
                      </div>
                      <div className="space-y-4">
                          <p className="text-[10px] font-black uppercase tracking-[0.2em] opacity-60">Core Principles</p>
                          <ul className="space-y-3">
                              {[
                                  { icon: ShieldCheck, text: 'Authorization Independence' },
                                  { icon: Zap, text: 'AI-Driven Efficiency' },
                                  { icon: Database, text: 'Structural Segregation' }
                              ].map((p, i) => (
                                  <li key={i} className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-widest">
                                      <p.icon className="h-3.5 w-3.5 opacity-60" /> {p.text}
                                  </li>
                              ))}
                          </ul>
                      </div>
                  </CardContent>
              </Card>

              <Card className="glass-card border-none">
                  <CardHeader><CardTitle className="text-xs font-black uppercase tracking-widest text-muted-foreground">Need Human Support?</CardTitle></CardHeader>
                  <CardContent className="space-y-4">
                      <p className="text-[10px] font-medium text-slate-400 leading-relaxed uppercase tracking-wider">If you encounter a protocol exception not covered in this manual, please raise a high-priority ticket in the helpdesk.</p>
                      <Button variant="secondary" className="w-full rounded-xl h-11 font-black uppercase tracking-widest text-[10px]" onClick={() => router.push('/helpdesk')}>
                          Open Helpdesk HUD <ChevronRight className="ml-2 h-4 w-4" />
                      </Button>
                  </CardContent>
              </Card>
          </div>
      </div>
    </div>
  );
}
